App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOperations:
    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [user_post]
      openapi_context:
        summary: Register a new user
    resend_activation_email:
      method: POST
      path: /users/resend_activation_email
      controller: App\Api\Action\User\ResendActivationEmail
      deserialize: false
      openapi_context:
        summary: Sends activation email to inactive user
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    required: true
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
  itemOperations:
    get:
      method: GET
